services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nuxt-network
    restart: unless-stopped
    command: sh -c "pnpm run db:push && pnpm dev"

  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nuxt-network
    restart: unless-stopped
    healthcheck:
      interval: 10s
      test: ['CMD-SHELL', 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"']
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  nuxt-network:
    driver: bridge
