--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg110+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fuzzystrmatch; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch WITH SCHEMA public;


--
-- Name: EXTENSION fuzzystrmatch; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION fuzzystrmatch IS 'determine similarities and distance between strings';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: postgis_tiger_geocoder; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder WITH SCHEMA tiger;


--
-- Name: EXTENSION postgis_tiger_geocoder; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_tiger_geocoder IS 'PostGIS tiger geocoder and reverse geocoder';


--
-- Name: postgis_topology; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;


--
-- Name: EXTENSION postgis_topology; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis_topology IS 'PostGIS topology spatial types and functions';


--
-- Name: detector_role; Type: TYPE; Schema: public; Owner: admin
--

CREATE TYPE public.detector_role AS ENUM (
    'Human',
    'Audio',
    'Video'
);


ALTER TYPE public.detector_role OWNER TO admin;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: admin
--

CREATE TYPE public.user_role AS ENUM (
    'Product Manager',
    'Contributor',
    'Admin'
);


ALTER TYPE public.user_role OWNER TO admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contact; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.contact (
    id bigint NOT NULL,
    detector_id bigint NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    type text NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.contact OWNER TO admin;

--
-- Name: contact_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detector; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.detector (
    id bigint NOT NULL,
    creator_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    serial_number text NOT NULL,
    model character varying(255) NOT NULL,
    brand character varying(255) NOT NULL,
    role public.detector_role NOT NULL
);


ALTER TABLE public.detector OWNER TO admin;

--
-- Name: detector_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.detector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project (
    id bigint NOT NULL,
    manager_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    private boolean NOT NULL,
    specie_id bigint NOT NULL,
    area public.geometry(Polygon,4326) NOT NULL
);


ALTER TABLE public.project OWNER TO admin;

--
-- Name: project_contributors; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_contributors (
    project_id bigint NOT NULL,
    contributor_id bigint NOT NULL
);


ALTER TABLE public.project_contributors OWNER TO admin;

--
-- Name: project_detectors; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_detectors (
    detector_id bigint NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.project_detectors OWNER TO admin;

--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_invite; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_invite (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.project_invite OWNER TO admin;

--
-- Name: project_invite_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.project_invite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_invite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_message; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_message (
    id bigint NOT NULL,
    sender_id bigint NOT NULL,
    project_id bigint NOT NULL,
    contact_id bigint NOT NULL,
    content text NOT NULL,
    issystemmessage boolean DEFAULT false NOT NULL
);


ALTER TABLE public.project_message OWNER TO admin;

--
-- Name: project_message_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.project_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_request; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_request (
    project_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    message text NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.project_request OWNER TO admin;

--
-- Name: project_request_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.project_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specie; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.specie (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    latin_name character varying(255) NOT NULL,
    acronym character varying(255) NOT NULL
);


ALTER TABLE public.specie OWNER TO admin;

--
-- Name: specie_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.specie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(320) NOT NULL,
    password text NOT NULL,
    role public.user_role DEFAULT 'Contributor'::public.user_role NOT NULL,
    phone text,
    avatar_url text
);


ALTER TABLE public."user" OWNER TO admin;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.contact (id, detector_id, "timestamp", type, geom) FROM stdin;
\.


--
-- Data for Name: detector; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.detector (id, creator_id, name, serial_number, model, brand, role) FROM stdin;
\.


--
-- Data for Name: project; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project (id, manager_id, name, description, start_date, end_date, private, specie_id, area) FROM stdin;
\.


--
-- Data for Name: project_contributors; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project_contributors (project_id, contributor_id) FROM stdin;
\.


--
-- Data for Name: project_detectors; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project_detectors (detector_id, project_id) FROM stdin;
\.


--
-- Data for Name: project_invite; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project_invite (project_id, user_id, id) FROM stdin;
\.


--
-- Data for Name: project_message; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project_message (id, sender_id, project_id, contact_id, content, issystemmessage) FROM stdin;
\.


--
-- Data for Name: project_request; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.project_request (project_id, requester_id, message, id) FROM stdin;
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Data for Name: specie; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.specie (id, name, latin_name, acronym) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."user" (id, username, email, password, role, phone, avatar_url) FROM stdin;
\.


--
-- Name: contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.contact_id_seq', 1, false);


--
-- Name: detector_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.detector_id_seq', 1, false);


--
-- Name: project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.project_id_seq', 1, false);


--
-- Name: project_invite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.project_invite_id_seq', 1, false);


--
-- Name: project_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.project_message_id_seq', 1, false);


--
-- Name: project_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.project_request_id_seq', 1, false);


--
-- Name: specie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.specie_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_id_seq', 1, false);


--
-- PostgreSQL database dump complete
--

